### ISSUE TITLE
体全体が上下する

### ISSUE THREAD

**Issue by kenkra** [miu200521358/VMD-3d-pose-baseline-multi#20]
1807行目（両足が埋まった時にセンターも一緒に上げる）の影響で、体全体が不自然に上下することがあります。

不自然な上下がなくなることを期待しています。単純に1807行目をコメントアウトして良いものかわからなかったためissuesにあげました。

サンプルのVMD（モデル：あにまさ式ミク、曲：SNOBBISM）を添付します。507Fなどで発生してます。
[output_20190105_175714_u02702_ganなし_h-0.7_xy50_z2.0_gx15_s1_間引きなし.zip](https://github.com/miu200521358/VMD-3d-pose-baseline-multi/files/2729409/output_20190105_175714_u02702_gan._h-0.7_xy50_z2.0_gx15_s1_.zip)
[output_20190105_180103_u02702_ganなし_h-0.7_xy50_z2.0_gx15_s1_間引きなし_センターは上げないVer.zip](https://github.com/miu200521358/VMD-3d-pose-baseline-multi/files/2729410/output_20190105_180103_u02702_gan._h-0.7_xy50_z2.0_gx15_s1_._.Ver.zip)

よろしくお願いします。

**Comment by miu200521358** [comment]
＞kenkra様

ご報告ありがとうございます。
ご提示のVMDですと、2477F目とかでしょうか。
調整対象とさせていただきます。
すみませんが、今しばらくお待ちください。

**Comment by miu200521358** [comment]
＞kenkra様

本件ですが、私の手元にある動画では、不自然な上下が見つけられなかったので、
お手数ですが、トレース元になった動画URLを教えて頂けませんでしょうか。
今回の修正にはまだ対応しておりません。
お手数をおかけして申し訳ありませんがご確認よろしくお願いいたします。

**Comment by kenkra** [comment]
miu様の動画では起きないのですね。ご確認ありがとうございます。
いったんクローズとさせてください。

今、私の方でも精度向上のためプログラム改変を行っています。最近やっと安定した結果がでるようになりました（私の手元にある動画の範囲で）。近いうちに紹介します。改修範囲が広いため簡単にはマージできないと思いますが、可能であればマージしたいと思っています。

**Comment by miu200521358** [comment]
Closeの件、了解いたしました。
精度向上の改変、ありがとうございます！
今回かなり大規模なコード改変を行ってしまい、すみません。
多分今回限りだと思いますが…
リクエスト、お待ちしております。

よろしければ、どのリポジトリに修正が入る予定かだけ教えていただいてもよろしいでしょうか。
次に複数人数のトレースを考えていて、そのために、深度推定と3d推定の順番を入れ替えようと考えています。
kenkra様の修正が入るようでしたら、しばらく触らないでおこうかと。

ご確認のほど、よろしくお願いいたします。
今後ともよろしくお願いいたします！
